version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=karen_user
      - POSTGRES_DB=inventory
    volumes:
      - "~/apps/postgres:/var/lib/postgresql/data"
